// 首次访问时自动初始化 8 张数据表
import { set, markInitialized, STORAGE_KEYS } from './storage'

export interface User { id: string; phone: string; password: string; name: string; gender: string; age: number; disease: string; disease_type: string; treatment_count: number; treatment_status: string; current_progress: string; improvement_rate: string; doctor: string; hospital: string; followup_count: number; avatar: string; created_at: string; updated_at: string; last_login: string; status: string; notes: string }
export interface ScienceItem { id: string; category: string; title: string; question: string; answer: string; read_count: number; collect_count: number; is_published: boolean; sort_order: number; author: string; tags: string[]; created_at: string; updated_at: string }
export interface VideoItem { id: string; category: string; title: string; description: string; cover_url: string; video_url: string; duration: string; author: string; views: number; created_at: string }
export interface FollowupQuestion { q_id: string; type: 'single' | 'multi' | 'rating' | 'text'; title: string; options: { o_id: string; text: string; score: number }[]; required: boolean; placeholder?: string }
export interface FollowupTemplate { id: string; name: string; version: string; description: string; is_active: boolean; questions: FollowupQuestion[]; created_at: string; updated_at: string }
export interface FollowupRecord { id: string; user_id: string; template_id: string; treatment_count: number; answers: Record<string, string | string[] | number>; total_score: number; submitted_at: string; status: '待填写' | '已提交' | '已查看' }
export interface MedicineItem { id: string; user_id: string; name: string; dosage: string; frequency: string; reminder_times: string[]; start_date: string; end_date: string; status: '服用中' | '已停药' | '已完成'; taken_dates: string[] }
export interface ReportIndicator { name: string; value: string; unit: string; range: string; status: '正常' | '偏高' | '偏低' }
export interface ReportItem { id: string; user_id: string; type: '血常规' | '肠道菌群检测' | '肝肾功能' | '电解质'; title: string; hospital: string; report_date: string; doctor: string; indicators: ReportIndicator[]; summary: string; created_at: string }
export interface KBItem { id: string; keywords: string[]; question: string; answer: string; category: string; hit_count: number; is_active: boolean }

export const defaultUsers: User[] = [
  { id: 'U_10001', phone: '13812340001', password: 'e10adc3949ba59abbe56e057f20f883e', name: '张三', gender: '男', age: 45, disease: '便秘', disease_type: '功能性便秘（慢传输型）', treatment_count: 3, treatment_status: '治疗中', current_progress: '第3次治疗已完成', improvement_rate: '明显改善', doctor: '王建国 主任医师', hospital: '上海市第一人民医院', followup_count: 2, avatar: '👤', created_at: '2025-10-15T08:30:00Z', updated_at: '2026-01-10T14:20:00Z', last_login: '2026-03-20T09:00:00Z', status: '正常', notes: '对青霉素轻度过敏' },
  { id: 'U_10002', phone: '13956780002', password: 'e10adc3949ba59abbe56e057f20f883e', name: '李梅花', gender: '女', age: 38, disease: '溃疡性结肠炎', disease_type: '中度活动期溃疡性结肠炎', treatment_count: 2, treatment_status: '治疗中', current_progress: '第2次治疗已完成', improvement_rate: '部分改善', doctor: '赵晓燕 副主任医师', hospital: '上海市第一人民医院', followup_count: 1, avatar: '👩', created_at: '2025-11-01T10:00:00Z', updated_at: '2025-11-20T16:00:00Z', last_login: '2026-03-18T15:30:00Z', status: '正常', notes: '有浅表性胃炎病史' },
  { id: 'U_10003', phone: '13698760003', password: 'e10adc3949ba59abbe56e057f20f883e', name: '王建国', gender: '男', age: 52, disease: '肠易激综合征', disease_type: '腹泻型肠易激综合征（IBS-D）', treatment_count: 1, treatment_status: '待启动第2次', current_progress: '第1次治疗已完成', improvement_rate: '良好', doctor: '王建国 主任医师', hospital: '上海市第一人民医院', followup_count: 1, avatar: '👨', created_at: '2025-12-05T09:15:00Z', updated_at: '2025-12-20T11:00:00Z', last_login: '2026-03-15T10:00:00Z', status: '正常', notes: '长期工作压力大，睡眠欠佳' },
  { id: 'U_10004', phone: '18823450004', password: 'e10adc3949ba59abbe56e057f20f883e', name: '陈小红', gender: '女', age: 29, disease: '便秘', disease_type: '顽固性便秘', treatment_count: 4, treatment_status: '已完成', current_progress: '第4次治疗已完成（疗程结束）', improvement_rate: '显著改善', doctor: '赵晓燕 副主任医师', hospital: '上海市第一人民医院', followup_count: 3, avatar: '👩', created_at: '2025-08-10T14:00:00Z', updated_at: '2026-01-25T10:30:00Z', last_login: '2026-03-10T11:00:00Z', status: '正常', notes: '产后便秘，持续2年' },
  { id: 'U_admin01', phone: 'admin', password: 'e10adc3949ba59abbe56e057f20f883e', name: '管理员', gender: '男', age: 30, disease: '', disease_type: '', treatment_count: 0, treatment_status: '', current_progress: '', improvement_rate: '', doctor: '', hospital: '', followup_count: 0, avatar: '🔐', created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z', last_login: '', status: '正常', notes: '系统管理员' },
]

export const defaultVideos: VideoItem[] = [
  { id: 'VID_001', category: '专家讲座', title: '周永健：粪菌移植治疗肠易激综合征', description: '广州市第一人民医院周永健教授讲解FMT在IBS治疗中的应用。', cover_url: 'https://picsum.photos/seed/fmt1/400/225', video_url: '', duration: '19分钟', author: '周永健 教授', views: 1256, created_at: '2026-03-20T00:00:00Z' },
  { id: 'VID_002', category: '专家讲座', title: '张婷：微生态用于儿童肠病治疗', description: '详细讲解儿童肠道微生态特点及FMT在儿童IBD、CDI等疾病中的应用。', cover_url: 'https://picsum.photos/seed/fmt2/400/225', video_url: '', duration: '22分钟', author: '张婷 教授', views: 987, created_at: '2026-03-20T00:00:00Z' },
  { id: 'VID_003', category: '治疗视频', title: 'FMT胶囊治疗操作演示', description: '展示FMT胶囊口服治疗的标准操作流程，包括服用前准备、服用方法、注意事项等。', cover_url: 'https://picsum.photos/seed/fmt3/400/225', video_url: '', duration: '8分钟', author: '上海市第一人民医院', views: 2341, created_at: '2026-03-20T00:00:00Z' },
  { id: 'VID_004', category: '治疗视频', title: '肠道菌群检测科普视频', description: '介绍肠道菌群检测的方法、指标解读以及如何通过饮食和FMT改善菌群状态。', cover_url: 'https://picsum.photos/seed/fmt4/400/225', video_url: '', duration: '12分钟', author: 'deepFMT团队', views: 1876, created_at: '2026-03-20T00:00:00Z' },
  { id: 'VID_005', category: '科普动画', title: '3分钟了解肠道菌群', description: '动画形式讲解人体肠道菌群的组成、功能，以及菌群失调与疾病的关系。', cover_url: 'https://picsum.photos/seed/fmt5/400/225', video_url: '', duration: '3分钟', author: 'deepFMT团队', views: 4521, created_at: '2026-03-20T00:00:00Z' },
  { id: 'VID_006', category: '科普动画', title: 'FMT治疗全流程动画', description: '动画展示FMT从供体筛查、菌液制备到患者移植的完整流程。', cover_url: 'https://picsum.photos/seed/fmt6/400/225', video_url: '', duration: '5分钟', author: 'deepFMT团队', views: 3298, created_at: '2026-03-20T00:00:00Z' },
]

export const defaultFollowupTemplates: FollowupTemplate[] = [
  { id: 'TPL_001', name: '标准7天随访问卷', version: 'v1.0', description: 'FMT治疗后7天标准随访问卷', is_active: true, questions: [
    { q_id: 'Q01', type: 'single', title: '治疗后腹痛情况如何？', options: [{ o_id: 'A', text: '无腹痛', score: 3 }, { o_id: 'B', text: '轻度（不影响日常）', score: 2 }, { o_id: 'C', text: '中度（部分影响）', score: 1 }, { o_id: 'D', text: '重度（严重影响）', score: 0 }], required: true },
    { q_id: 'Q02', type: 'single', title: '治疗后腹泻情况如何？', options: [{ o_id: 'A', text: '正常', score: 3 }, { o_id: 'B', text: '轻微腹泻', score: 2 }, { o_id: 'C', text: '中度腹泻', score: 1 }, { o_id: 'D', text: '严重腹泻', score: 0 }], required: true },
    { q_id: 'Q03', type: 'rating', title: '整体症状改善程度（1-5星）', options: [], required: true },
    { q_id: 'Q04', type: 'multi', title: '出现了哪些不适？（可多选）', options: [{ o_id: 'A', text: '腹胀', score: 0 }, { o_id: 'B', text: '腹泻', score: 0 }, { o_id: 'C', text: '发热', score: 0 }, { o_id: 'D', text: '恶心', score: 0 }, { o_id: 'E', text: '无明显不适', score: 3 }], required: true },
    { q_id: 'Q05', type: 'single', title: '是否遵医嘱按时服药？', options: [{ o_id: 'A', text: '完全遵医嘱', score: 3 }, { o_id: 'B', text: '偶尔漏服', score: 2 }, { o_id: 'C', text: '经常漏服', score: 1 }, { o_id: 'D', text: '自行停药', score: 0 }], required: true },
    { q_id: 'Q06', type: 'rating', title: '食欲改善程度（1-5星）', options: [], required: true },
    { q_id: 'Q07', type: 'single', title: '总体改善情况？', options: [{ o_id: 'A', text: '明显改善', score: 4 }, { o_id: 'B', text: '部分改善', score: 3 }, { o_id: 'C', text: '无变化', score: 1 }, { o_id: 'D', text: '加重', score: 0 }], required: true },
    { q_id: 'Q08', type: 'text', title: '还有其他想告诉医生的吗？', options: [], required: false, placeholder: '请描述您的情况或疑问...' },
  ], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' }
]

export const defaultFollowupRecords: FollowupRecord[] = [
  { id: 'REC_001', user_id: 'U_10001', template_id: 'TPL_001', treatment_count: 3, answers: { Q01: 'B', Q02: 'A', Q03: 4, Q04: 'E', Q05: 'A', Q06: 4, Q07: 'A', Q08: '服药期间一切正常' }, total_score: 22, submitted_at: '2026-01-10T14:20:00Z', status: '已查看' },
  { id: 'REC_002', user_id: 'U_10002', template_id: 'TPL_001', treatment_count: 2, answers: { Q01: 'C', Q02: 'B', Q03: 3, Q04: 'A', Q05: 'A', Q06: 3, Q07: 'B', Q08: '偶有腹胀，食欲一般' }, total_score: 16, submitted_at: '2025-11-20T16:00:00Z', status: '已查看' },
  { id: 'REC_003', user_id: 'U_10003', template_id: 'TPL_001', treatment_count: 1, answers: { Q01: 'A', Q02: 'A', Q03: 5, Q04: 'E', Q05: 'A', Q06: 5, Q07: 'A', Q08: '效果很好，感谢医生' }, total_score: 23, submitted_at: '2025-12-20T11:00:00Z', status: '已查看' },
]

export const defaultMedicines: MedicineItem[] = [
  { id: 'MED_001', user_id: 'U_10001', name: '双歧杆菌胶囊', dosage: '每日2次，每次3粒', frequency: '每日2次', reminder_times: ['08:00', '20:00'], start_date: '2025-10-15', end_date: '2026-04-15', status: '服用中', taken_dates: ['2026-03-17', '2026-03-18', '2026-03-19'] },
  { id: 'MED_002', user_id: 'U_10001', name: '益生元冲剂', dosage: '每日1次，每次1袋', frequency: '每日1次', reminder_times: ['08:30'], start_date: '2025-10-15', end_date: '2026-04-15', status: '服用中', taken_dates: ['2026-03-17', '2026-03-18', '2026-03-19'] },
  { id: 'MED_003', user_id: 'U_10002', name: '美沙拉嗪肠溶片', dosage: '每日4次，每次1g', frequency: '每日4次', reminder_times: ['07:00', '12:00', '18:00', '22:00'], start_date: '2025-11-01', end_date: '2026-05-01', status: '服用中', taken_dates: ['2026-03-17', '2026-03-18', '2026-03-19'] },
  { id: 'MED_004', user_id: 'U_10002', name: '复合益生菌胶囊', dosage: '每日2次，每次2粒', frequency: '每日2次', reminder_times: ['09:00', '21:00'], start_date: '2025-11-01', end_date: '2026-05-01', status: '服用中', taken_dates: ['2026-03-17', '2026-03-18', '2026-03-19'] },
]

export const defaultReports: ReportItem[] = [
  { id: 'RPT_001', user_id: 'U_10001', type: '血常规', title: '血常规检查报告', hospital: '上海市第一人民医院', report_date: '2026-01-05', doctor: '王建国 主任医师', indicators: [
    { name: '白细胞计数', value: '6.5', unit: 'x10^9/L', range: '3.5-9.5', status: '正常' },
    { name: '红细胞计数', value: '4.8', unit: 'x10^12/L', range: '4.3-5.9', status: '正常' },
    { name: '血红蛋白', value: '145', unit: 'g/L', range: '130-175', status: '正常' },
    { name: '血小板计数', value: '218', unit: 'x10^9/L', range: '125-350', status: '正常' },
    { name: '中性粒细胞比例', value: '58', unit: '%', range: '40-75', status: '正常' },
    { name: '淋巴细胞比例', value: '35', unit: '%', range: '20-50', status: '正常' },
  ], summary: '血常规各项指标均在正常范围内，无明显异常发现。', created_at: '2026-01-05T10:00:00Z' },
  { id: 'RPT_002', user_id: 'U_10001', type: '肠道菌群检测', title: '肠道菌群检测报告', hospital: '上海市第一人民医院', report_date: '2025-12-15', doctor: '王建国 主任医师', indicators: [
    { name: '菌群多样性指数', value: '3.2', unit: '', range: '2.5-4.0', status: '正常' },
    { name: '双歧杆菌', value: '8.5x10^8', unit: 'CFU/g', range: '>1.0x10^6', status: '正常' },
    { name: '乳酸杆菌', value: '6.2x10^7', unit: 'CFU/g', range: '>1.0x10^5', status: '正常' },
    { name: '肠杆菌', value: '5.1x10^6', unit: 'CFU/g', range: '<1.0x10^8', status: '正常' },
    { name: '产丁酸菌', value: '偏低', unit: '', range: '正常', status: '偏低' },
  ], summary: '肠道菌群多样性处于正常范围，主要有益菌含量正常，产丁酸菌含量略偏低，建议继续补充益生菌。', created_at: '2025-12-15T14:00:00Z' },
]

export const defaultChatKB: KBItem[] = [
  { id: 'KB_001', keywords: ['FMT', '粪菌', '移植', '是什么', '定义'], question: 'FMT是什么？', answer: '粪菌移植（FMT）是将健康供体粪便中的功能菌群移植到患者肠道内，重建微生态平衡的创新疗法。2013年起FDA批准用于复发性艰难梭菌感染（CDI），我国2022年发布操作规范。目前主要通过口服胶囊、结肠镜等方式进行移植。', category: '基础知识', hit_count: 0, is_active: true },
  { id: 'KB_002', keywords: ['便秘', '排便困难', '大便干结'], question: '便秘怎么治疗？', answer: 'FMT治疗便秘的主要原理是通过移植健康菌群，改善肠道微生态环境，促进肠道蠕动功能。研究表明，便秘型肠易激综合征（IBS-C）患者接受FMT治疗后，60%-80%可获得症状改善，排便频率增加、腹胀减轻。建议在专业医生指导下进行系统治疗，同时配合膳食纤维摄入、适量运动等。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_003', keywords: ['安全', '危险', '副作用', '不良反应', '并发症'], question: 'FMT安全吗？', answer: 'FMT总体安全性良好。常见不良反应多为轻微自限性，包括腹胀（约20%）、排气增多（15%）、轻度腹泻（10%）、短暂低热（5%）等，通常在1-3天内自行缓解。严重并发症罕见。在正规医疗机构由专业团队操作，严格筛查供体，可进一步保障安全性。', category: '基础知识', hit_count: 0, is_active: true },
  { id: 'KB_004', keywords: ['适应症', '适应', '哪些疾病', '可以治疗'], question: 'FMT的适应症有哪些？', answer: '根据中国专家共识（2022版），FMT适应症包括：①复发性艰难梭菌感染（CDI），有效率>90%；②炎症性肠病（溃疡性结肠炎），有效率约50-60%；③肠易激综合征（IBS），有效率约60-80%；④功能性便秘；⑤代谢综合征（肥胖、糖尿病）；⑥自闭症、帕金森病等肠-脑轴相关疾病。需专业医生评估后决定。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_005', keywords: ['注意事项', '注意', '禁忌', '不能做'], question: '哪些人不能做FMT？', answer: 'FMT禁忌人群：①绝对禁忌：肠梗阻、消化道穿孔、严重消化道出血、肠坏死、急腹症；②重度免疫缺陷（AIDS晚期）；③严重心肺功能不全；④妊娠期（除非紧急CDI）；⑤对FMT成分严重过敏者。相对禁忌：⑥中度免疫抑制；⑦活动性感染；⑧严重肝肾功能不全；⑨恶性肿瘤等。需由专业医生评估后决定。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_006', keywords: ['腹泻', '拉肚子', '大便稀'], question: '腹泻可以用FMT治疗吗？', answer: '可以，FMT对多种原因引起的腹泻有治疗效果，特别是：①艰难梭菌感染性腹泻（CDI）：FMT有效率>90%；②抗菌药相关性腹泻：FMT可帮助恢复肠道菌群；③肠易激综合征腹泻型（IBS-D）：多项RCT显示FMT有效（60-80%）；④炎症性肠病相关腹泻：部分患者可获缓解。具体方案需由医生根据病因决定。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_007', keywords: ['移植', '流程', '步骤', '方法'], question: 'FMT是怎么移植的？', answer: 'FMT主要移植方式：①口服胶囊（最常用，方便无创）：每次15-30粒，冷水送服；②结肠镜移植（精准）：通过结肠镜将菌液喷洒至回肠/结肠，20-30分钟；③鼻肠管移植：经鼻腔置管至十二指肠；④灌肠（居家便捷）：经肛门灌入保留20-30min。口服胶囊目前最常用，方便且创伤最小。', category: '流程', hit_count: 0, is_active: true },
  { id: 'KB_008', keywords: ['饮食', '吃什么', '食谱', '忌口'], question: 'FMT后饮食有什么要求？', answer: 'FMT后饮食原则：循序渐进、清淡易消化。①移植后2-4h：温热流质（小米粥汤、藕粉）；②第1-3天：半流质为主（白粥、面条、蒸蛋），少量多餐5-6次/天；③第4-7天：软食过渡（软米饭、炖菜）；④1周后：正常均衡饮食，增加酸奶、燕麦等。禁忌：高糖高脂饮食、酒精。推荐地中海饮食模式。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_009', keywords: ['效果', '见效', '多久', '多长时间'], question: 'FMT后多久能看到效果？', answer: 'FMT起效时间因病而异：①复发性CDI：最快，24-48小时内症状改善，2-3天完全缓解；②功能性便秘：1-2周排便改善，部分需2-4周；③肠易激综合征：2-4周腹痛腹胀逐步改善；④炎症性肠病：较慢，通常需4-8周才观察明显改善。建议第2、4、8周分别评估症状改善情况。', category: '流程', hit_count: 0, is_active: true },
  { id: 'KB_010', keywords: ['IBS', '肠易激', '综合征'], question: '肠易激综合征（IBS）可以用FMT治疗吗？', answer: '可以，FMT是IBS的有效治疗手段。IBS以腹痛伴排便习惯改变为特征，全球患病率约11%。多项RCT显示FMT对IBS有效（尤其腹泻型IBS-D和便秘型IBS-C）。原理：调节菌群改善肠道通透性，减少内脏高敏感性，改善腹痛和排便。治疗建议2-4次移植，每2-4周1次，联合低FODMAP饮食效果更佳。有效率约60-80%。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_011', keywords: ['IBD', '溃疡性结肠炎', '克罗恩', '结肠炎'], question: '溃疡性结肠炎可以用FMT治疗吗？', answer: '溃疡性结肠炎（UC）FMT疗效有较多循证证据，多项RCT显示FMT可诱导UC临床及内镜缓解。2019年Gastroenterology发表迄今最大规模RCT（84例），FMT组缓解率27% vs 对照组8%。克罗恩病（CD）证据相对少，部分患者可获临床缓解。FMT通过补充产丁酸盐菌、重建黏膜屏障、调节免疫起效，通常作为综合治疗一部分。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_012', keywords: ['CDI', '艰难梭菌', '感染'], question: '艰难梭菌感染（CDI）可以用FMT治疗吗？', answer: '可以，FMT是治疗复发性CDI的标准方案。传统抗生素复发率35-65%，FMT单次有效率>90%，多次累计有效率接近100%。流程：①停用抗生素>=48小时；②口服泻药清肠；③口服胶囊或结肠镜移植；④观察24-48小时。治疗后2小时内避免卧床，24小时内避免使用抗生素（除非病情必需）。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_013', keywords: ['儿童', '小孩', '幼儿', '儿科'], question: '儿童可以接受FMT治疗吗？', answer: '可以，儿童FMT已在CDI和儿童IBD方面有丰富经验。儿童FMT特点：①供体必须使用儿童供体（<12岁），菌群组成更适合儿童肠道；②首选鼻肠管或灌肠（儿童难以配合大量口服胶囊）；③不良反应与成人相当或更低；④需监护人知情同意；⑤剂量按体重调整（5-10g粪便/kg）。在艰难梭菌感染、溃疡性结肠炎等方面均有成功案例。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_014', keywords: ['老年人', '老人', '高龄'], question: '老年人可以接受FMT治疗吗？', answer: '可以，老年人是FMT的重要受益人群。"菌群老化"使老年人便秘、CDI、感染风险升高。老年FMT注意：①评估抗凝药、免疫抑制剂风险；②80岁以上优先口服胶囊或灌肠（结肠镜风险增加）；③剂量与成人一致；④老年患者不良反应未见显著高于年轻患者；⑤需家属/护理人员协助服药观察。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_015', keywords: ['孕妇', '怀孕', '妊娠'], question: '孕妇可以接受FMT治疗吗？', answer: '妊娠期FMT需谨慎。原则上妊娠期属于FMT的相对禁忌（除非紧急CDI）。如果孕妇发生复发性CDI（危及生命），FMT可能是唯一有效治疗手段，此时需充分权衡利弊，由产科、感染科、肠胃科多学科评估后决定。非紧急情况下，建议待分娩后再进行FMT治疗。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_016', keywords: ['益生菌', '益生元', '补充'], question: 'FMT后需要吃益生菌吗？', answer: '建议在医生指导下补充益生菌/益生元。FMT后肠道菌群处于"重建期"，适当补充有助于：①巩固FMT移植的有益菌；②填充菌群"空白期"，减少致病菌定植；③促进短链脂肪酸产生，加速肠黏膜修复。推荐含双歧杆菌、乳酸杆菌的复合制剂，移植后1-2周开始服用，连续3-6个月。具体请遵医嘱。', category: '流程', hit_count: 0, is_active: true },
  { id: 'KB_017', keywords: ['副作用', '发烧', '发热', '腹胀'], question: 'FMT后发烧正常吗？', answer: 'FMT后发热需区分情况：①短暂低热（<38度）：约5%患者出现，通常在移植后24小时内自行退热，属于正常免疫调节反应，无需特殊处理，多饮水、观察即可；②持续高热（>38.5度）或发热超过48小时：需立即就医；③伴随严重腹痛、血便、皮疹：立即就医，可能是严重并发症信号。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_018', keywords: ['抗生素', '药物', '服用'], question: 'FMT期间可以服用其他药物吗？', answer: 'FMT期间药物使用注意：①抗生素：FMT后24-48小时内避免使用（除紧急必需），因抗生素会杀灭移植的菌群；②质子泵抑制剂（PPI）：理论上可能影响FMT效果，建议咨询医生；③免疫抑制剂（IBD患者）：在医生指导下可继续使用，不突然停药；④益生菌：FMT后1-2周开始补充有益；⑤中药：部分中药可能影响菌群，建议间隔使用。具体请遵医嘱。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_019', keywords: ['供体', '筛选', '来源'], question: 'FMT的供体是怎么筛选的？', answer: '供体筛查严格程度超过无偿献血：①流行病学调查：排除高风险行为、旅游史（疟疾、寨卡疫区）；②血液/粪便检测40余项：HIV/HBV/HCV/梅毒等传染病，艰难梭菌、寄生虫、致病菌培养；③定期复查：每3-6个月复查感染指标。儿童FMT需用儿童供体。正规机构批量化生产标准化菌液，质量稳定。', category: '基础知识', hit_count: 0, is_active: true },
  { id: 'KB_020', keywords: ['治疗', '次数', '疗程'], question: 'FMT需要做多少次？能一次治好吗？', answer: '治疗次数因病而异：①复发性CDI：通常1次，约90%单次治愈；②功能性便秘：轻症1-2次，中重度2-4次；③IBS：通常2-4次，间隔2-4周；④IBD：诱导缓解需3-6次，维持治疗视情况而定。FMT并非一次治愈的万能疗法，多数疾病需要完整疗程，医生会定期评估效果决定是否追加。', category: '流程', hit_count: 0, is_active: true },
  { id: 'KB_021', keywords: ['准备', '清肠', '术前'], question: 'FMT治疗前需要做哪些准备？', answer: 'FMT前准备：①治疗前1周：停用抗生素，避免服用益生菌/益生元；②治疗前3天：清淡少渣饮食（稀饭、面条、蒸蛋），避免高纤维和乳制品；③治疗前1天：流质饮食，按医嘱服用泻药（聚乙二醇4000散/乳果糖）清肠至水样便；④治疗当日：空腹，带齐病历，女性避开月经期。', category: '流程', hit_count: 0, is_active: true },
  { id: 'KB_022', keywords: ['复查', '随访', '监测'], question: 'FMT后需要定期复查吗？', answer: 'FMT后需要定期复查。复查时间：①CDI：通常无需长期复查，复发时再检；②IBD/IBS/便秘：建议移植后2周、4周、8周、12周各复查1次。复查项目：①症状评估（腹痛、排便情况、生活质量）；②粪便常规加钙卫蛋白（IBD监测）；③必要时粪便微生物检测；④必要时血液检查。具体由医生根据病情决定。', category: '注意事项', hit_count: 0, is_active: true },
  { id: 'KB_023', keywords: ['自闭症', '孤独症', 'ASD', '帕金森', '抑郁'], question: 'FMT可以治疗自闭症或帕金森病吗？', answer: 'FMT通过"肠-脑轴"对部分神经系统疾病有潜力：①自闭症谱系障碍（ASD）：约30-50%ASD儿童伴胃肠道症状，2019年Cell杂志RCT（18例儿童）显示FMT后胃肠道症状减少80%，ASD评分改善；②帕金森病：便秘是其早期症状，FMT可能改善运动症状；③抑郁症：初步研究显示FMT可改善情绪评分。需更大规模RCT验证，目前仍属研究性治疗。', category: '适应症', hit_count: 0, is_active: true },
  { id: 'KB_024', keywords: ['效果', '维持', '复发', '长期'], question: 'FMT的效果能维持多久？', answer: 'FMT效果因病而异：①复发性CDI：多为一次性治愈，1年复发率<10%，长期效果稳定；②炎症性肠病：效果持续时间差异较大，部分患者可维持1-2年，部分患者需定期维持治疗；③IBS：多数患者效果持续6-12个月，部分需补充治疗。延长效果建议：联合益生元/益生菌补充、避免抗生素滥用、维持健康饮食和生活方式。', category:'基础知识', hit_count: 0, is_active: true },
]

export const defaultScience: ScienceItem[] = [
  { id: 'SCI_001', category: '基础知识', title: '什么是粪菌移植（FMT）？', question: '什么是粪菌移植（FMT）？', answer: '粪菌移植（FMT）是将健康供体粪便中的功能菌群通过特定方式移植到患者肠道内，重建微生态平衡的创新疗法。2013年FDA批准用于CDI，我国2022年发布《肠道菌群移植技术操作规范》。主要方式：口服胶囊、结肠镜，鼻肠管、灌肠。', read_count: 482, collect_count: 87, is_published: true, sort_order: 1, author: '管理员', tags: ['FMT', '粪菌移植', '基础知识'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_002', category: '基础知识', title: 'FMT的基本原理是什么？', question: 'FMT的基本原理是什么？', answer: 'FMT原理基于菌群-肠-多器官轴：①菌群竞争；②功能补充短链脂肪酸产生菌；③免疫调节降低促炎因子；④代谢调控改善胆汁酸；⑤肠-脑轴调节影响中枢神经。', read_count: 356, collect_count: 63, is_published: true, sort_order: 2, author: '管理员', tags: ['原理', '机制', '肠-脑轴'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_003', category: '基础知识', title: '肠道菌群与人体健康有什么关系？', question: '肠道菌群与人体健康有什么关系？', answer: '人体肠道内约38万亿个细菌、1000余种，被称为被遗忘的器官。正常肠道菌群参与：①消化吸收；②免疫调节（占IgA的70%）；③维生素合成（K、B族）；④药物代谢；⑤神经发育。菌群失调可导致感染、炎症、代谢病等。', read_count: 521, collect_count: 92, is_published: true, sort_order: 3, author: '管理员', tags: ['肠道菌群', '健康', '微生物'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_004', category: '基础知识', title: 'FMT安全吗？有哪些副作用？', question: 'FMT安全吗？有哪些副作用？', answer: 'FMT总体安全性良好。常见轻微反应：①腹胀/排气增多（约20%）；②轻度腹泻（约10%）；③短暂低热（<5%）；④恶心；⑤皮疹（罕见）。严重并发症发生率<0.1%。免疫缺陷、严重肠梗阻等为禁忌。', read_count: 498, collect_count: 95, is_published: true, sort_order: 4, author: '管理员', tags: ['安全性', '副作用', '风险'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_005', category: '基础知识', title: 'FMT有哪些移植方式？', question: 'FMT有哪些移植方式？', answer: 'FMT主要方式：①口服胶囊（最常用，方便无创）：每次15-30粒；②结肠镜移植（精准）：20-30分钟；③鼻肠管移植；④灌肠（居家便捷）；⑤联合方式。具体方案由医生根据病情决定。', read_count: 287, collect_count: 54, is_published: true, sort_order: 5, author: '管理员', tags: ['移植方式', '胶囊', '结肠镜'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_006', category: '基础知识', title: 'FMT的供体是怎么筛选的？', question: 'FMT的供体是怎么筛选的？', answer: '供体筛查严格程度超过无偿献血：①流行病学调查：排除高风险行为、旅游史；②血液/粪便检测40余项：HIV/HBV/HCV/梅毒等传染病，艰难梭菌、寄生虫；③定期复查：每3-6个月复查感染指标。儿童FMT需用儿童供体。', read_count: 234, collect_count: 41, is_published: true, sort_order: 6, author: '管理员', tags: ['供体', '筛查', '安全'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_007', category: '基础知识', title: 'FMT治疗需要多长时间？需要做几次？', question: 'FMT治疗需要多长时间？需要做几次？', answer: 'FMT疗程因病而异：①复发性CDI：1-3次，有效率>90%；②IBD：3-6次，每2-4周1次，疗程3-6个月；③IBS：2-4次，间隔2-4周；④功能性便秘：1-3次。单次移植约20-30分钟。', read_count: 312, collect_count: 58, is_published: true, sort_order: 7, author: '管理员', tags: ['疗程', '治疗次数', '周期'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_008', category: '基础知识', title: 'FMT的效果能维持多久？会复发吗？', question: 'FMT的效果能维持多久？会复发吗？', answer: 'FMT效果因病而异：①复发性CDI：多为一次性治愈，1年复发率<10%；②IBD：部分维持1-2年；③IBS：效果持续6-12个月。延长效果建议联合益生元/益生菌补充、避免抗生素滥用、维持健康饮食。', read_count: 198, collect_count: 37, is_published: true, sort_order: 8, author: '管理员', tags: ['效果', '维持', '复发'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_009', category: '基础知识', title: 'FMT在中国的发展历史是什么？', question: 'FMT在中国的发展历史是什么？', answer: 'FMT中国历史：①1700年前葛洪《肘后备急方》记载；②2012年中国菌群移植平台建立；③2015年张发明团队完成中国首例FMT；④2022年《肠道菌群移植技术操作规范》发布；⑤2024年《临床应用管理规范》发布。目前全国超300家中心开展FMT。', read_count: 165, collect_count: 28, is_published: true, sort_order: 9, author: '管理员', tags: ['历史', '中国', '发展'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_010', category: '适应症', title: 'FMT能治疗哪些疾病？', question: 'FMT能治疗哪些疾病？', answer: 'FMT适应症分两类。指南推荐：①复发性艰难梭菌感染（rCDI），有效率>90%；②炎症性肠病（溃疡性结肠炎为主），有效率约50-60%；③肠易激综合征（IBS），有效率约60-80%；④功能性便秘，有效率约70%。研究探索：⑤代谢综合征；⑥自闭症谱系障碍；⑦肝性脑病等。需专业医生评估。', read_count: 445, collect_count: 88, is_published: true, sort_order: 10, author: '管理员', tags: ['适应症', '疾病', '病种'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_011', category: '适应症', title: '复发性艰难梭菌感染（CDI）可以用FMT治疗吗？', question: '复发性艰难梭菌感染（CDI）可以用FMT治疗吗？', answer: '可以，FMT是治疗复发性CDI的标准方案。传统抗生素复发率35-65%，FMT单次有效率>90%，多次累计有效率接近100%。流程：①停用抗生素>=48小时；②口服泻药清肠；③口服胶囊或结肠镜移植；④观察24-48小时。', read_count: 287, collect_count: 52, is_published: true, sort_order: 11, author: '管理员', tags: ['CDI', '艰难梭菌', '感染'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_012', category: '适应症', title: '溃疡性结肠炎和克罗恩病可以用FMT治疗吗？', question: '溃疡性结肠炎和克罗恩病可以用FMT治疗吗？', answer: '溃疡性结肠炎（UC）FMT疗效有较多循证证据，多项RCT显示FMT可诱导UC临床及内镜缓解。2019年Gastroenterology发表迄今最大规模RCT（84例），FMT组缓解率27% vs 对照组8%。克罗恩病（CD）证据相对少。FMT通过补充产丁酸盐菌、重建黏膜屏障、调节免疫起效。', read_count: 334, collect_count: 61, is_published: true, sort_order: 12, author: '管理员', tags: ['IBD', '溃疡性结肠炎', '克罗恩病'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_013', category: '适应症', title: '肠易激综合征（IBS）可以用FMT治疗吗？', question: '肠易激综合征（IBS）可以用FMT治疗吗？', answer: '可以，FMT是IBS的有效治疗手段。IBS以腹痛伴排便习惯改变为特征，全球患病率约11%。多项RCT显示FMT对IBS有效（尤其IBS-D和IBS-C）。原理：调节菌群改善肠道通透性，减少内脏高敏感性。治疗建议2-4次移植，联合低FODMAP饮食。有效率约60-80%。', read_count: 298, collect_count: 55, is_published: true, sort_order: 13, author: '管理员', tags: ['IBS', '肠易激综合征', '便秘', '腹泻'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_014', category: '适应症', title: '功能性便秘可以用FMT治疗吗？', question: '功能性便秘可以用FMT治疗吗？', answer: '可以，FMT对功能性便秘效果良好，尤其慢传输型便秘（STC）。机制：①补充产气细菌改善肠道动力；②调节胆汁酸代谢促进蠕动；③恢复肠道神经-肌肉协调。FMT后排便频率从每周1-2次增加至3-5次，腹胀减轻。推荐方案1-3次移植，间隔2-4周。', read_count: 256, collect_count: 48, is_published: true, sort_order: 14, author: '管理员', tags: ['便秘', '功能性便秘', '慢传输型'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_015', category: '适应症', title: '儿童可以接受FMT治疗吗？', question: '儿童可以接受FMT治疗吗？', answer: '可以，儿童FMT已在CDI和儿童IBD方面有丰富经验。儿童FMT特点：①供体必须使用儿童供体（<12岁）；②首选鼻肠管或灌肠；③不良反应与成人相当或更低；④需监护人知情同意；⑤剂量按体重调整（5-10g粪便/kg）。', read_count: 189, collect_count: 34, is_published: true, sort_order: 15, author: '管理员', tags: ['儿童', '儿科', '幼儿'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_016', category: '适应症', title: '老年人可以接受FMT治疗吗？', question: '老年人可以接受FMT治疗吗？', answer: '可以，老年人是FMT的重要受益人群。菌群老化使老年人便秘、CDI、感染风险升高。老年FMT注意：①评估抗凝药、免疫抑制剂风险；②80岁以上优先口服胶囊或灌肠；③剂量与成人一致；④老年患者不良反应未见显著高于年轻患者。', read_count: 156, collect_count: 27, is_published: true, sort_order: 16, author: '管理员', tags: ['老年人', '老年', '高龄'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_017', category: '适应症', title: 'FMT可以治疗糖尿病、肥胖等代谢性疾病吗？', question: 'FMT可以治疗糖尿病、肥胖等代谢性疾病吗？', answer: 'FMT对部分代谢性疾病有潜力但多为研究阶段：①2型糖尿病：初步研究显示FMT可改善胰岛素敏感性，降低血糖，效果有限；②肥胖：效果不确切；③非酒精性脂肪肝：FMT可改善肝脏脂肪变性和肝酶水平；④代谢病FMT目前仍属研究性治疗。', read_count: 223, collect_count: 39, is_published: true, sort_order: 17, author: '管理员', tags: ['糖尿病', '肥胖', '代谢综合征'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_018', category: '适应症', title: 'FMT可以治疗自闭症、帕金森病等神经系统疾病吗？', question: 'FMT可以治疗自闭症、帕金森病等神经系统疾病吗？', answer: 'FMT通过肠-脑轴对部分神经系统疾病有潜力：①自闭症谱系障碍（ASD）：约30-50%ASD儿童伴胃肠道症状，2019年Cell杂志RCT显示FMT后胃肠道症状减少80%，ASD评分改善；②帕金森病：便秘是其早期症状，FMT可能改善运动症状；③抑郁症：初步研究显示FMT可改善情绪评分。需更大规模RCT验证。', read_count: 267, collect_count: 45, is_published: true, sort_order: 18, author: '管理员', tags: ['自闭症', '帕金森', '肠-脑轴', '神经'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_019', category: '流程', title: 'FMT治疗前需要做哪些准备？', question: 'FMT治疗前需要做哪些准备？', answer: 'FMT前准备：①治疗前1周：停用抗生素，避免服用益生菌/益生元；②治疗前3天：清淡少渣饮食（稀饭、面条、蒸蛋），避免高纤维和乳制品；③治疗前1天：流质饮食，按医嘱服用泻药清肠至水样便；④治疗当日：空腹，带齐病历，女性避开月经期。', read_count: 387, collect_count: 72, is_published: true, sort_order: 19, author: '管理员', tags: ['准备', '流程', '清肠'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_020', category: '流程', title: 'FMT治疗当天是什么流程？', question: 'FMT治疗当天是什么流程？', answer: 'FMT当天流程（口服胶囊）：①挂号报到，携带有效证件；②签署知情同意书；③领取菌液/胶囊，核对姓名、批次号、有效期；④空腹服用，30-50ml冷水送服，勿咀嚼；⑤在院观察30-60分钟；⑥2小时内避免平卧，2小时后可正常活动和进食。', read_count: 298, collect_count: 56, is_published: true, sort_order: 20, author: '管理员', tags: ['流程', '当天', '胶囊'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_021', category: '流程', title: 'FMT移植后需要注意什么？', question: 'FMT移植后需要注意什么？', answer: 'FMT后注意事项：①活动：卧床休息2小时（可坐起），2小时后可正常活动，避免剧烈运动；②饮食：2小时后从清淡流质逐步过渡，24小时内避免生冷辛辣油腻；③用药：24-48小时内避免抗生素（除非必需），遵医嘱补充益生元/益生菌；④观察：严重腹痛>6/10、持续高热>38.5度、血便需立即就医。', read_count: 412, collect_count: 78, is_published: true, sort_order: 21, author: '管理员', tags: ['术后', '注意事项', '恢复'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_022', category: '流程', title: 'FMT后饮食有什么要求？', question: 'FMT后饮食有什么要求？', answer: 'FMT后饮食原则：循序渐进、清淡易消化。①移植后2-4h：温热流质（小米粥汤、藕粉）；②第1-3天：半流质为主（白粥、面条、蒸蛋），少量多餐；③第4-7天：软食过渡（软米饭、炖菜、鱼肉）；④1周后：正常均衡饮食，增加酸奶、燕麦等。禁忌：高糖高脂饮食、酒精。推荐地中海饮食模式。', read_count: 276, collect_count: 51, is_published: true, sort_order: 22, author: '管理员', tags: ['饮食', '食谱', '营养'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_023', category: '流程', title: 'FMT后多久能看到效果？', question: 'FMT后多久能看到效果？', answer: 'FMT起效时间因病而异：①复发性CDI：最快，24-48小时内症状改善，2-3天完全缓解；②功能性便秘：1-2周排便改善，部分需2-4周；③IBS：2-4周腹痛腹胀逐步改善；④IBD：较慢，通常需4-8周才观察明显改善。建议第2、4、8周分别评估。', read_count: 234, collect_count: 43, is_published: true, sort_order: 23, author: '管理员', tags: ['效果', '见效', '评估'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_024', category: '流程', title: 'FMT需要做多少次？能一次治好吗？', question: 'FMT需要做多少次？能一次治好吗？', answer: '治疗次数因病而异：①复发性CDI：通常1次，约90%单次治愈；②功能性便秘：轻症1-2次，中重度2-4次；③IBS：通常2-4次；④IBD：诱导缓解需3-6次。FMT并非一次治愈的万能疗法，多数疾病需要完整疗程，医生会定期评估效果决定是否追加。', read_count: 289, collect_count: 47, is_published: true, sort_order: 24, author: '管理员', tags: ['次数', '疗程', '频率'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_025', category: '流程', title: 'FMT后需要吃益生菌吗？', question: 'FMT后需要吃益生菌吗？', answer: '建议在医生指导下补充益生菌/益生元。FMT后肠道菌群处于重建期，适当补充有助于：①巩固FMT移植的有益菌；②填充菌群空白期，减少致病菌定植；③促进短链脂肪酸产生，加速肠黏膜修复。推荐含双歧杆菌、乳酸杆菌的复合制剂，移植后1-2周开始服用，连续3-6个月。', read_count: 321, collect_count: 59, is_published: true, sort_order: 25, author: '管理员', tags: ['益生菌', '术后', '补充'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_026', category: '流程', title: 'FMT后多久可以正常生活和工作？', question: 'FMT后多久可以正常生活和工作？', answer: 'FMT后恢复时间：①当天：避免剧烈运动，2小时后正常活动；②1-3天：部分患者有轻微腹胀、排气增多，不影响日常工作；③4-7天：可恢复正常生活和工作，忌重体力劳动；④完全恢复：大多数人在1周内完全恢复。', read_count: 187, collect_count: 31, is_published: true, sort_order: 26, author: '管理员', tags: ['恢复', '生活', '工作'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_027', category: '流程', title: 'FMT期间可以接种疫苗吗？', question: 'FMT期间可以接种疫苗吗？', answer: 'FMT期间疫苗接种需谨慎：①灭活疫苗（如流感疫苗、乙肝疫苗）：FMT后2周可接种；②减毒活疫苗（如麻腮风、水痘）：建议FMT后4-8周再接种；③新冠疫苗：参考当地指南，通常FMT后2-4周可接种；④其他疫苗：接种前请告知医生FMT治疗史。', read_count: 143, collect_count: 22, is_published: true, sort_order: 27, author: '管理员', tags: ['疫苗', '接种', '免疫'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_028', category: '注意事项', title: '哪些人不能做FMT？', question: '哪些人不能做FMT？', answer: 'FMT禁忌人群：①绝对禁忌：肠梗阻、消化道穿孔、严重消化道出血、肠坏死、急腹症；②重度免疫缺陷（CD4<200）；③严重心肺功能不全；④妊娠期（除非紧急CDI）；⑤对FMT成分严重过敏者。相对禁忌：⑥中度免疫抑制；⑦活动性感染；⑧严重肝肾功能不全；⑨恶性肿瘤等。需由专业医生评估后决定。', read_count: 334, collect_count: 65, is_published: true, sort_order: 28, author: '管理员', tags: ['禁忌', '不能做', '注意事项'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_029', category: '注意事项', title: 'FMT期间可以服用其他药物吗？', question: 'FMT期间可以服用其他药物吗？', answer: 'FMT期间药物使用注意：①抗生素：FMT后24-48小时内避免使用（除紧急必需），因抗生素会杀灭移植的菌群；②质子泵抑制剂（PPI）：理论上可能影响FMT效果，建议咨询医生；③免疫抑制剂（IBD患者）：在医生指导下可继续使用，不突然停药；④益生菌：FMT后1-2周开始补充有益。', read_count: 289, collect_count: 44, is_published: true, sort_order: 29, author: '管理员', tags: ['药物', '用药', '注意事项'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_030', category: '注意事项', title: 'FMT移植后需要忌口吗？', question: 'FMT移植后需要忌口吗？有哪些饮食禁忌？', answer: 'FMT后饮食禁忌：①移植后24小时内：避免生冷、辛辣、油腻；②1周内：避免高糖高脂饮食，减少加工食品摄入；③长期：限制酒精摄入（移植后1个月避免）。鼓励：酸奶（无糖）、燕麦、全谷物、蔬菜水果（逐步添加）、坚果。地中海饮食模式最有利于维持菌群多样性。', read_count: 267, collect_count: 48, is_published: true, sort_order: 30, author: '管理员', tags: ['饮食', '忌口', '禁忌'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_031', category: '注意事项', title: 'FMT后发烧正常吗？', question: 'FMT后发烧怎么办？', answer: 'FMT后发热需区分情况：①短暂低热（<38度）：约5%患者出现，通常在移植后24小时内自行退热，属于正常免疫调节反应；②持续高热（>38.5度）或发热超过48小时：需立即就医；③伴随严重腹痛、血便、皮疹：立即就医，可能是严重并发症信号。建议移植后常规监测体温，异常及时联系医生。', read_count: 234, collect_count: 41, is_published: true, sort_order: 31, author: '管理员', tags: ['发烧', '发热', '异常'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_032', category: '注意事项', title: 'FMT后出现腹泻正常吗？', question: 'FMT后出现腹泻怎么办？', answer: 'FMT后腹泻分情况：①轻微腹泻（1-3次/天，稀便）：约10%患者出现，通常在移植后1-3天自行缓解，属于菌群调整的正常反应；②中重度腹泻（>3次/天，水样便）：需密切观察，补充口服补液盐（ORS），避免脱水；③腹泻伴高热、血便、腹痛加剧：立即就医。', read_count: 198, collect_count: 35, is_published: true, sort_order: 32, author: '管理员', tags: ['腹泻', '肠胃', '异常'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_033', category: '注意事项', title: 'FMT后腹胀正常吗？', question: 'FMT后腹胀排气多正常吗？', answer: 'FMT后腹胀和排气增多是正常现象，发生率约20%，通常在移植后1-3天自行缓解。这是因为移植的菌群在肠道内定植、发酵，产生气体所致。处理方法：①顺时针按摩腹部促进排气；②温热敷腹部；③适度活动（散步）促进肠蠕动；④薄荷茶或陈皮茶有助缓解；⑤避免豆类、洋葱等产气食物。如腹胀持续超过1周需及时就医。', read_count: 178, collect_count: 29, is_published: true, sort_order: 33, author: '管理员', tags: ['腹胀', '排气', '正常'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_034', category: '注意事项', title: 'FMT后可以洗澡吗？可以运动吗？', question: 'FMT后可以洗澡吗？可以运动吗？', answer: 'FMT后日常活动：①洗澡：移植后当天即可洗澡，淋浴为宜，避免桑拿超过15分钟；②运动：移植后2小时内避免剧烈运动，2小时后可轻度活动（散步），1周内避免游泳、健身、举重等。可逐步恢复，从快走开始，2周后恢复正常运动强度。', read_count: 145, collect_count: 21, is_published: true, sort_order: 34, author: '管理员', tags: ['洗澡', '运动', '日常'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_035', category: '注意事项', title: 'FMT后需要定期复查吗？复查哪些项目？', question: 'FMT后需要定期复查吗？复查哪些项目？', answer: 'FMT后需要定期复查。复查时间：①CDI：通常无需长期复查，复发时再检；②IBD/IBS/便秘：建议移植后2周、4周、8周、12周各复查1次。复查项目：①症状评估；②粪便常规加钙卫蛋白（IBD监测）；③必要时粪便微生物检测；④必要时血液检查。具体复查项目由医生根据病情决定。', read_count: 167, collect_count: 26, is_published: true, sort_order: 35, author: '管理员', tags: ['复查', '随访', '监测'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'SCI_036', category: '注意事项', title: 'FMT后为什么还要长期管理肠道健康？', question: 'FMT后为什么还要长期管理肠道健康？', answer: 'FMT不是一劳永逸的治疗，长期肠道健康管理非常重要：①肠道菌群容易受饮食、抗生素、压力等因素影响而再次失调；②部分患者可能需要维持治疗（如IBD）来保持效果；③长期管理措施包括：均衡饮食（地中海饮食）、规律运动、充足睡眠、减少不必要抗生素使用、补充益生菌、定期复查。FMT与健康生活方式结合，才能实现长期稳定的治疗效果。', read_count: 189, collect_count: 32, is_published: true, sort_order: 36, author: '管理员', tags: ['长期管理', '肠道健康', '预防'], created_at: '2026-03-20T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
]

export function initData() {
  set(STORAGE_KEYS.USERS, defaultUsers)
  set(STORAGE_KEYS.SCIENCE, defaultScience)
  set(STORAGE_KEYS.VIDEOS, defaultVideos)
  set(STORAGE_KEYS.FOLLOWUP_TEMPLATES, defaultFollowupTemplates)
  set(STORAGE_KEYS.FOLLOWUP_RECORDS, defaultFollowupRecords)
  set(STORAGE_KEYS.MEDICINE, defaultMedicines)
  set(STORAGE_KEYS.REPORTS, defaultReports)
  set(STORAGE_KEYS.CHAT_KB, defaultChatKB)
  markInitialized()
}

export function ensureInitialized() {
  if (!localStorage.getItem(STORAGE_KEYS.INIT_FLAG)) {
    initData()
  }
}
